/*
 * This is a generated file. Do not edit.
 *
 * File generated by solenv/bin/native-code.py
 */

#include <config_features.h>
#include <osl/detail/component-mapping.h>

extern "C" {

void * analysis_component_getFactory( const char* , void* , void* );
void * comphelp_component_getFactory( const char* , void* , void* );
void * configmgr_component_getFactory( const char* , void* , void* );
void * date_component_getFactory( const char* , void* , void* );
void * deployment_component_getFactory( const char* , void* , void* );
void * drawinglayer_component_getFactory( const char* , void* , void* );
void * embobj_component_getFactory( const char* , void* , void* );
void * emboleobj_component_getFactory( const char* , void* , void* );
void * evtatt_component_getFactory( const char* , void* , void* );
void * filterconfig1_component_getFactory( const char* , void* , void* );
void * fsstorage_component_getFactory( const char* , void* , void* );
void * hyphen_component_getFactory( const char* , void* , void* );
void * i18npool_component_getFactory( const char* , void* , void* );
void * i18nsearch_component_getFactory( const char* , void* , void* );
void * invocadapt_component_getFactory( const char* , void* , void* );
void * lng_component_getFactory( const char* , void* , void* );
void * lnth_component_getFactory( const char* , void* , void* );
void * localebe1_component_getFactory( const char* , void* , void* );
void * mtfrenderer_component_getFactory( const char* , void* , void* );
void * odfflatxml_component_getFactory( const char* , void* , void* );
void * oox_component_getFactory( const char* , void* , void* );
void * package2_component_getFactory( const char* , void* , void* );
void * pricing_component_getFactory( const char* , void* , void* );
void * reflection_component_getFactory( const char* , void* , void* );
void * sc_component_getFactory( const char* , void* , void* );
void * sd_component_getFactory( const char* , void* , void* );
void * sm_component_getFactory( const char* , void* , void* );
void * srtrs1_component_getFactory( const char* , void* , void* );
void * storagefd_component_getFactory( const char* , void* , void* );
void * svgfilter_component_getFactory( const char* , void* , void* );
void * svgio_component_getFactory( const char* , void* , void* );
void * sw_component_getFactory( const char* , void* , void* );
void * ucb_component_getFactory( const char* , void* , void* );
void * ucpfile_component_getFactory( const char* , void* , void* );
void * ucphier1_component_getFactory( const char* , void* , void* );
void * ucptdoc1_component_getFactory( const char* , void* , void* );
void * unordf_component_getFactory( const char* , void* , void* );
void * unoxml_component_getFactory( const char* , void* , void* );
void * utl_component_getFactory( const char* , void* , void* );
void * vclcanvas_component_getFactory( const char* , void* , void* );
void * xmlfa_component_getFactory( const char* , void* , void* );
void * xmlfd_component_getFactory( const char* , void* , void* );
void * xmlscript_component_getFactory( const char* , void* , void* );
void * xmlsecurity_component_getFactory( const char* , void* , void* );
void * xof_component_getFactory( const char* , void* , void* );
void * xo_component_getFactory( const char* , void* , void* );
#if !defined ANDROID && !defined IOS
void * xsec_xmlsec_component_getFactory( const char* , void* , void* );
#endif
void * xstor_component_getFactory( const char* , void* , void* );

void * Calc_XMLOasisContentExporter_get_implementation( void *, void * );
void * Calc_XMLOasisExporter_get_implementation( void *, void * );
void * Calc_XMLOasisMetaExporter_get_implementation( void *, void * );
void * Calc_XMLOasisSettingsExporter_get_implementation( void *, void * );
void * Calc_XMLOasisStylesExporter_get_implementation( void *, void * );
void * IndexedPropertyValuesContainer_get_implementation( void *, void * );
void * Math_XMLOasisMetaExporter_get_implementation( void *, void * );
void * Math_XMLOasisSettingsExporter_get_implementation( void *, void * );
void * NamedPropertyValuesContainer_get_implementation( void *, void * );
void * RandomAnimationNode_get_implementation( void *, void * );
void * SfxDocumentMetaData_get_implementation( void *, void * );
void * XMLVersionListPersistence_get_implementation( void *, void * );
void * com_sun_star_animations_AnimateColor_get_implementation( void *, void * );
void * com_sun_star_animations_AnimateMotion_get_implementation( void *, void * );
void * com_sun_star_animations_AnimateSet_get_implementation( void *, void * );
void * com_sun_star_animations_AnimateTransform_get_implementation( void *, void * );
void * com_sun_star_animations_Animate_get_implementation( void *, void * );
void * com_sun_star_animations_Audio_get_implementation( void *, void * );
void * com_sun_star_animations_Command_get_implementation( void *, void * );
void * com_sun_star_animations_IterateContainer_get_implementation( void *, void * );
void * com_sun_star_animations_ParallelTimeContainer_get_implementation( void *, void * );
void * com_sun_star_animations_SequenceTimeContainer_get_implementation( void *, void * );
void * com_sun_star_animations_TransitionFilter_get_implementation( void *, void * );
void * com_sun_star_chart2_LinearScaling_get_implementation( void *, void * );
void * com_sun_star_comp_Draw_GraphicExporter_get_implementation( void *, void * );
void * com_sun_star_comp_Draw_framework_BasicPaneFactory_get_implementation( void *, void * );
void * com_sun_star_comp_Draw_framework_BasicToolBarFactory_get_implementation( void *, void * );
void * com_sun_star_comp_Draw_framework_BasicViewFactory_get_implementation( void *, void * );
void * com_sun_star_comp_Draw_framework_PresentationFactoryProvider_get_implementation( void *, void * );
void * com_sun_star_comp_Draw_framework_ResourceID_get_implementation( void *, void * );
void * com_sun_star_comp_Draw_framework_configuration_ConfigurationController_get_implementation( void *, void * );
void * com_sun_star_comp_Draw_framework_module_ModuleController_get_implementation( void *, void * );
void * com_sun_star_comp_MemoryStream( void *, void * );
void * com_sun_star_comp_SequenceInputStreamService( void *, void * );
void * com_sun_star_comp_SequenceOutputStreamService( void *, void * );
void * com_sun_star_comp_Svx_GraphicExportHelper_get_implementation( void *, void * );
void * com_sun_star_comp_Svx_GraphicImportHelper_get_implementation( void *, void * );
void * com_sun_star_comp_Writer_RtfFilter_get_implementation( void *, void * );
void * com_sun_star_comp_Writer_WriterFilter_get_implementation( void *, void * );
void * com_sun_star_comp_Writer_XMLOasisContentExporter_get_implementation( void *, void * );
void * com_sun_star_comp_Writer_XMLOasisContentImporter_get_implementation( void *, void * );
void * com_sun_star_comp_Writer_XMLOasisImporter_get_implementation( void *, void * );
void * com_sun_star_comp_Writer_XMLOasisMetaExporter_get_implementation( void *, void * );
void * com_sun_star_comp_Writer_XMLOasisMetaImporter_get_implementation( void *, void * );
void * com_sun_star_comp_Writer_XMLOasisSettingsExporter_get_implementation( void *, void * );
void * com_sun_star_comp_Writer_XMLOasisSettingsImporter_get_implementation( void *, void * );
void * com_sun_star_comp_Writer_XMLOasisStylesExporter_get_implementation( void *, void * );
void * com_sun_star_comp_Writer_XMLOasisStylesImporter_get_implementation( void *, void * );
void * com_sun_star_comp_calc_ExcelBiffFormatDetector_get_implementation( void *, void * );
void * com_sun_star_comp_calc_FormatDetector_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_Axis_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_ChartController_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_ChartDocumentWrapper_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_ChartFrameLoader_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_ChartModel_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_Diagram_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_ErrorBar_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_LabeledDataSequence_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_Legend_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_LinearRegressionCurve_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_PolarCoordinateSystem2d_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_PolarCoordinateSystem3d_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_PolynomialRegressionCurve_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_PotentialRegressionCurve_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_RegressionEquation_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_Title_get_implementation( void *, void * );
void * com_sun_star_comp_chart2_XMLFilter_get_implementation( void *, void * );
void * com_sun_star_comp_chart_AreaChartType_get_implementation( void *, void * );
void * com_sun_star_comp_chart_BarChartType_get_implementation( void *, void * );
void * com_sun_star_comp_chart_BubbleChartType_get_implementation( void *, void * );
void * com_sun_star_comp_chart_CandleStickChartType_get_implementation( void *, void * );
void * com_sun_star_comp_chart_ChartTypeManager_get_implementation( void *, void * );
void * com_sun_star_comp_chart_ColumnChartType_get_implementation( void *, void * );
void * com_sun_star_comp_chart_DataSeries_get_implementation( void *, void * );
void * com_sun_star_comp_chart_DataSource_get_implementation( void *, void * );
void * com_sun_star_comp_chart_FilledNetChartType_get_implementation( void *, void * );
void * com_sun_star_comp_chart_FormattedString_get_implementation( void *, void * );
void * com_sun_star_comp_chart_GL3DBarChartType_get_implementation( void *, void * );
void * com_sun_star_comp_chart_LineChartType_get_implementation( void *, void * );
void * com_sun_star_comp_chart_NetChartType_get_implementation( void *, void * );
void * com_sun_star_comp_chart_PieChartType_get_implementation( void *, void * );
void * com_sun_star_comp_chart_ScatterChartType_get_implementation( void *, void * );
void * com_sun_star_comp_comphelper_OPropertyBag( void *, void * );
void * com_sun_star_comp_dba_ORowSet_get_implementation( void *, void * );
void * com_sun_star_comp_draw_FormatDetector_get_implementation( void *, void * );
void * com_sun_star_comp_embed_OLESimpleStorage( void *, void * );
void * com_sun_star_comp_extensions_xml_sax_FastParser_get_implementation( void *, void * );
void * com_sun_star_comp_extensions_xml_sax_ParserExpat_get_implementation( void *, void * );
void * com_sun_star_comp_filters_PlainTextFilterDetect_get_implementation( void *, void * );
void * com_sun_star_comp_forms_FormOperations_get_implementation( void *, void * );
void * com_sun_star_comp_forms_ODatabaseForm_get_implementation( void *, void * );
void * com_sun_star_comp_forms_OFormattedFieldWrapper_ForcedFormatted_get_implementation( void *, void * );
void * com_sun_star_comp_forms_ORichTextModel_get_implementation( void *, void * );
void * com_sun_star_comp_forms_OScrollBarModel_get_implementation( void *, void * );
void * com_sun_star_comp_forms_OSpinButtonModel_get_implementation( void *, void * );
void * com_sun_star_comp_framework_AutoRecovery_get_implementation( void *, void * );
void * com_sun_star_comp_framework_Desktop_get_implementation( void *, void * );
void * com_sun_star_comp_framework_DocumentAcceleratorConfiguration_get_implementation( void *, void * );
void * com_sun_star_comp_framework_Frame_get_implementation( void *, void * );
void * com_sun_star_comp_framework_GlobalAcceleratorConfiguration_get_implementation( void *, void * );
void * com_sun_star_comp_framework_JobExecutor_get_implementation( void *, void * );
void * com_sun_star_comp_framework_LayoutManager_get_implementation( void *, void * );
void * com_sun_star_comp_framework_ModuleAcceleratorConfiguration_get_implementation( void *, void * );
void * com_sun_star_comp_framework_ModuleManager_get_implementation( void *, void * );
void * com_sun_star_comp_framework_ModuleUIConfigurationManagerSupplier_get_implementation( void *, void * );
void * com_sun_star_comp_framework_ModuleUIConfigurationManager_get_implementation( void *, void * );
void * com_sun_star_comp_framework_PathSettings_get_implementation( void *, void * );
void * com_sun_star_comp_framework_PathSubstitution_get_implementation( void *, void * );
void * com_sun_star_comp_framework_SoundHandler_get_implementation( void *, void * );
void * com_sun_star_comp_framework_StatusIndicatorFactory_get_implementation( void *, void * );
void * com_sun_star_comp_framework_TaskCreator_get_implementation( void *, void * );
void * com_sun_star_comp_framework_ToolBarControllerFactory_get_implementation( void *, void * );
void * com_sun_star_comp_framework_UIConfigurationManager_get_implementation( void *, void * );
void * com_sun_star_comp_framework_UIElementFactoryManager_get_implementation( void *, void * );
void * com_sun_star_comp_framework_URLTransformer_get_implementation( void *, void * );
void * com_sun_star_comp_framework_WindowStateConfiguration_get_implementation( void *, void * );
void * com_sun_star_comp_graphic_GraphicProvider_get_implementation( void *, void * );
void * com_sun_star_comp_graphic_PrimitiveFactory2D_get_implementation( void *, void * );
void * com_sun_star_comp_logging_SimpleLogRing( void *, void * );
void * com_sun_star_comp_office_FrameLoader_get_implementation( void *, void * );
void * com_sun_star_comp_oox_xls_ExcelFilter_get_implementation( void *, void * );
void * com_sun_star_comp_oox_xls_FormulaParser_get_implementation( void *, void * );
void * com_sun_star_comp_rendering_CanvasFactory_get_implementation( void *, void * );
void * com_sun_star_comp_sfx2_AppDispatchProvider_get_implementation( void *, void * );
void * com_sun_star_comp_sfx2_DocumentTemplates_get_implementation( void *, void * );
void * com_sun_star_comp_sfx2_GlobalEventBroadcaster_get_implementation( void *, void * );
#if HAVE_FEATURE_SCRIPTING
void * com_sun_star_comp_sfx2_ScriptLibraryContainer_get_implementation( void *, void * );
#endif
void * com_sun_star_comp_stoc_Introspection_get_implementation( void *, void * );
void * com_sun_star_comp_stoc_OServiceManagerWrapper_get_implementation( void *, void * );
void * com_sun_star_comp_stoc_TypeConverter_get_implementation( void *, void * );
void * com_sun_star_comp_task_OfficeRestartManager( void *, void * );
void * com_sun_star_comp_uri_ExternalUriReferenceTranslator_get_implementation( void *, void * );
void * com_sun_star_comp_uri_UriReferenceFactory_get_implementation( void *, void * );
void * com_sun_star_comp_uri_UriSchemeParser_vndDOTsunDOTstarDOTexpand_get_implementation( void *, void * );
void * com_sun_star_comp_uri_UriSchemeParser_vndDOTsunDOTstarDOTscript_get_implementation( void *, void * );
void * com_sun_star_comp_uui_UUIInteractionHandler_get_implementation( void *, void * );
void * com_sun_star_comp_writer_FormatDetector_get_implementation( void *, void * );
void * com_sun_star_drawing_EnhancedCustomShapeEngine_get_implementation( void *, void * );
void * com_sun_star_drawing_SvxShapeCollection_get_implementation( void *, void * );
void * com_sun_star_extensions_xml_sax_Writer_get_implementation( void *, void * );
void * com_sun_star_form_Model_get_implementation( void *, void * );
void * com_sun_star_form_OButtonControl_get_implementation( void *, void * );
void * com_sun_star_form_OButtonModel_get_implementation( void *, void * );
void * com_sun_star_form_OCheckBoxControl_get_implementation( void *, void * );
void * com_sun_star_form_OCheckBoxModel_get_implementation( void *, void * );
void * com_sun_star_form_OComboBoxControl_get_implementation( void *, void * );
void * com_sun_star_form_OComboBoxModel_get_implementation( void *, void * );
void * com_sun_star_form_ODateControl_get_implementation( void *, void * );
void * com_sun_star_form_ODateModel_get_implementation( void *, void * );
void * com_sun_star_form_OEditControl_get_implementation( void *, void * );
void * com_sun_star_form_OEditModel_get_implementation( void *, void * );
void * com_sun_star_form_OFixedTextModel_get_implementation( void *, void * );
void * com_sun_star_form_OFormsCollection_get_implementation( void *, void * );
void * com_sun_star_form_OGridControlModel_get_implementation( void *, void * );
void * com_sun_star_form_OGroupBoxModel_get_implementation( void *, void * );
void * com_sun_star_form_OListBoxModel_get_implementation( void *, void * );
void * com_sun_star_form_ONumericModel_get_implementation( void *, void * );
void * com_sun_star_form_ORadioButtonModel_get_implementation( void *, void * );
void * com_sun_star_form_XForms_get_implementation( void *, void * );
void * com_sun_star_graphic_GraphicObject_get_implementation( void *, void * );
void * com_sun_star_i18n_BreakIterator_Unicode_get_implementation( void *, void * );
void * com_sun_star_i18n_BreakIterator_get_implementation( void *, void * );
void * com_sun_star_i18n_CharacterClassification_Unicode_get_implementation( void *, void * );
void * com_sun_star_i18n_CharacterClassification_get_implementation( void *, void * );
void * com_sun_star_i18n_Collator_get_implementation( void *, void * );
void * com_sun_star_i18n_InputSequenceChecker_get_implementation( void *, void * );
void * com_sun_star_i18n_LocaleDataImpl_get_implementation( void *, void * );
void * com_sun_star_i18n_NativeNumberSupplier_get_implementation( void *, void * );
void * com_sun_star_i18n_NumberFormatCodeMapper_get_implementation( void *, void * );
void * com_sun_star_i18n_OrdinalSuffix_get_implementation( void *, void * );
void * com_sun_star_i18n_Transliteration_IGNORE_CASE_get_implementation( void *, void * );
void * com_sun_star_i18n_Transliteration_IGNORE_KANA_get_implementation( void *, void * );
void * com_sun_star_i18n_Transliteration_IGNORE_WIDTH_get_implementation( void *, void * );
void * com_sun_star_i18n_Transliteration_get_implementation( void *, void * );
void * com_sun_star_text_DefaultNumberingProvider_get_implementation( void *, void * );
void * com_sun_star_uno_util_numbers_SvNumberFormatsSupplierServiceObject_get_implementation( void *, void * );
void * com_sun_star_uno_util_numbers_SvNumberFormatterServiceObject_get_implementation( void *, void * );
void * com_sun_star_util_comp_FinalThreadManager_get_implementation( void *, void * );
#if HAVE_FEATURE_SCRIPTING
void * ooo_vba_VBAToOOEventDesc_get_implementation( void *, void * );
#endif
void * org_apache_openoffice_comp_framework_ContextChangeEventMultiplexer_get_implementation( void *, void * );
void * stardiv_Toolkit_StdTabController_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoButtonControl_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoCheckBoxControl_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoComboBoxControl_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoControlButtonModel_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoControlCheckBoxModel_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoControlComboBoxModel_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoControlContainerModel_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoControlContainer_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoControlDateFieldModel_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoControlDialogModel_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoControlFixedTextModel_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoControlFormattedFieldModel_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoControlGroupBoxModel_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoControlListBoxModel_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoControlNumericFieldModel_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoControlRadioButtonModel_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoControlScrollBarModel_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoDateFieldControl_get_implementation( void *, void * );
void * stardiv_Toolkit_UnoSpinButtonModel_get_implementation( void *, void * );
void * stardiv_Toolkit_VCLXPointer_get_implementation( void *, void * );
void * stardiv_Toolkit_VCLXToolkit_get_implementation( void *, void * );

const lib_to_factory_mapping *
lo_get_factory_map(void)
{
    static lib_to_factory_mapping map[] = {
        { "libanalysislo.a", analysis_component_getFactory },
        { "libcomphelper.a", comphelp_component_getFactory },
        { "libconfigmgrlo.a", configmgr_component_getFactory },
        { "libdatelo.a", date_component_getFactory },
        { "libdeployment.a", deployment_component_getFactory },
        { "libdrawinglayerlo.a", drawinglayer_component_getFactory },
        { "libembobj.a", embobj_component_getFactory },
        { "libemboleobj.a", emboleobj_component_getFactory },
        { "libevtattlo.a", evtatt_component_getFactory },
        { "libfilterconfiglo.a", filterconfig1_component_getFactory },
        { "libfsstoragelo.a", fsstorage_component_getFactory },
        { "libhyphenlo.a", hyphen_component_getFactory },
        { "libi18npoollo.a", i18npool_component_getFactory },
        { "libi18nsearchlo.a", i18nsearch_component_getFactory },
        { "libinvocadaptlo.a", invocadapt_component_getFactory },
        { "liblnglo.a", lng_component_getFactory },
        { "liblnthlo.a", lnth_component_getFactory },
        { "liblocalebe1lo.a", localebe1_component_getFactory },
        { "libmtfrendererlo.a", mtfrenderer_component_getFactory },
        { "libodfflatxmllo.a", odfflatxml_component_getFactory },
        { "libooxlo.a", oox_component_getFactory },
        { "libpackage2.a", package2_component_getFactory },
        { "libpricinglo.a", pricing_component_getFactory },
        { "libreflectionlo.a", reflection_component_getFactory },
        { "libsclo.a", sc_component_getFactory },
        { "libsdlo.a", sd_component_getFactory },
        { "libsmlo.a", sm_component_getFactory },
        { "libsrtrs1.a", srtrs1_component_getFactory },
        { "libstoragefdlo.a", storagefd_component_getFactory },
        { "libsvgfilterlo.a", svgfilter_component_getFactory },
        { "libsvgiolo.a", svgio_component_getFactory },
        { "libswlo.a", sw_component_getFactory },
        { "libucb1.a", ucb_component_getFactory },
        { "libucpfile1.a", ucpfile_component_getFactory },
        { "libucphier1.a", ucphier1_component_getFactory },
        { "libucptdoc1lo.a", ucptdoc1_component_getFactory },
        { "libunordflo.a", unordf_component_getFactory },
        { "libunoxmllo.a", unoxml_component_getFactory },
        { "libutllo.a", utl_component_getFactory },
        { "libvclcanvaslo.a", vclcanvas_component_getFactory },
        { "libxmlfalo.a", xmlfa_component_getFactory },
        { "libxmlfdlo.a", xmlfd_component_getFactory },
        { "libxmlscriptlo.a", xmlscript_component_getFactory },
        { "libxmlsecurity.a", xmlsecurity_component_getFactory },
        { "libxoflo.a", xof_component_getFactory },
        { "libxolo.a", xo_component_getFactory },
#if !defined ANDROID && !defined IOS
        { "libxsec_xmlsec.a", xsec_xmlsec_component_getFactory },
#endif
        { "libxstor.a", xstor_component_getFactory },

        { 0, 0 }
    };

    extern void Java_org_libreoffice_kit_LibreOfficeKit_initializeNative();
    volatile void *p = (void *) Java_org_libreoffice_kit_LibreOfficeKit_initializeNative;

    extern void Java_org_libreoffice_kit_Office_getError();
    p = (void *) Java_org_libreoffice_kit_Office_getError;

    

    return map;
}

const lib_to_constructor_mapping *
lo_get_constructor_map(void)
{
    static lib_to_constructor_mapping map[] = {
        { "Calc_XMLOasisContentExporter_get_implementation", Calc_XMLOasisContentExporter_get_implementation },
        { "Calc_XMLOasisExporter_get_implementation", Calc_XMLOasisExporter_get_implementation },
        { "Calc_XMLOasisMetaExporter_get_implementation", Calc_XMLOasisMetaExporter_get_implementation },
        { "Calc_XMLOasisSettingsExporter_get_implementation", Calc_XMLOasisSettingsExporter_get_implementation },
        { "Calc_XMLOasisStylesExporter_get_implementation", Calc_XMLOasisStylesExporter_get_implementation },
        { "IndexedPropertyValuesContainer_get_implementation", IndexedPropertyValuesContainer_get_implementation },
        { "Math_XMLOasisMetaExporter_get_implementation", Math_XMLOasisMetaExporter_get_implementation },
        { "Math_XMLOasisSettingsExporter_get_implementation", Math_XMLOasisSettingsExporter_get_implementation },
        { "NamedPropertyValuesContainer_get_implementation", NamedPropertyValuesContainer_get_implementation },
        { "RandomAnimationNode_get_implementation", RandomAnimationNode_get_implementation },
        { "SfxDocumentMetaData_get_implementation", SfxDocumentMetaData_get_implementation },
        { "XMLVersionListPersistence_get_implementation", XMLVersionListPersistence_get_implementation },
        { "com_sun_star_animations_AnimateColor_get_implementation", com_sun_star_animations_AnimateColor_get_implementation },
        { "com_sun_star_animations_AnimateMotion_get_implementation", com_sun_star_animations_AnimateMotion_get_implementation },
        { "com_sun_star_animations_AnimateSet_get_implementation", com_sun_star_animations_AnimateSet_get_implementation },
        { "com_sun_star_animations_AnimateTransform_get_implementation", com_sun_star_animations_AnimateTransform_get_implementation },
        { "com_sun_star_animations_Animate_get_implementation", com_sun_star_animations_Animate_get_implementation },
        { "com_sun_star_animations_Audio_get_implementation", com_sun_star_animations_Audio_get_implementation },
        { "com_sun_star_animations_Command_get_implementation", com_sun_star_animations_Command_get_implementation },
        { "com_sun_star_animations_IterateContainer_get_implementation", com_sun_star_animations_IterateContainer_get_implementation },
        { "com_sun_star_animations_ParallelTimeContainer_get_implementation", com_sun_star_animations_ParallelTimeContainer_get_implementation },
        { "com_sun_star_animations_SequenceTimeContainer_get_implementation", com_sun_star_animations_SequenceTimeContainer_get_implementation },
        { "com_sun_star_animations_TransitionFilter_get_implementation", com_sun_star_animations_TransitionFilter_get_implementation },
        { "com_sun_star_chart2_LinearScaling_get_implementation", com_sun_star_chart2_LinearScaling_get_implementation },
        { "com_sun_star_comp_Draw_GraphicExporter_get_implementation", com_sun_star_comp_Draw_GraphicExporter_get_implementation },
        { "com_sun_star_comp_Draw_framework_BasicPaneFactory_get_implementation", com_sun_star_comp_Draw_framework_BasicPaneFactory_get_implementation },
        { "com_sun_star_comp_Draw_framework_BasicToolBarFactory_get_implementation", com_sun_star_comp_Draw_framework_BasicToolBarFactory_get_implementation },
        { "com_sun_star_comp_Draw_framework_BasicViewFactory_get_implementation", com_sun_star_comp_Draw_framework_BasicViewFactory_get_implementation },
        { "com_sun_star_comp_Draw_framework_PresentationFactoryProvider_get_implementation", com_sun_star_comp_Draw_framework_PresentationFactoryProvider_get_implementation },
        { "com_sun_star_comp_Draw_framework_ResourceID_get_implementation", com_sun_star_comp_Draw_framework_ResourceID_get_implementation },
        { "com_sun_star_comp_Draw_framework_configuration_ConfigurationController_get_implementation", com_sun_star_comp_Draw_framework_configuration_ConfigurationController_get_implementation },
        { "com_sun_star_comp_Draw_framework_module_ModuleController_get_implementation", com_sun_star_comp_Draw_framework_module_ModuleController_get_implementation },
        { "com_sun_star_comp_MemoryStream", com_sun_star_comp_MemoryStream },
        { "com_sun_star_comp_SequenceInputStreamService", com_sun_star_comp_SequenceInputStreamService },
        { "com_sun_star_comp_SequenceOutputStreamService", com_sun_star_comp_SequenceOutputStreamService },
        { "com_sun_star_comp_Svx_GraphicExportHelper_get_implementation", com_sun_star_comp_Svx_GraphicExportHelper_get_implementation },
        { "com_sun_star_comp_Svx_GraphicImportHelper_get_implementation", com_sun_star_comp_Svx_GraphicImportHelper_get_implementation },
        { "com_sun_star_comp_Writer_RtfFilter_get_implementation", com_sun_star_comp_Writer_RtfFilter_get_implementation },
        { "com_sun_star_comp_Writer_WriterFilter_get_implementation", com_sun_star_comp_Writer_WriterFilter_get_implementation },
        { "com_sun_star_comp_Writer_XMLOasisContentExporter_get_implementation", com_sun_star_comp_Writer_XMLOasisContentExporter_get_implementation },
        { "com_sun_star_comp_Writer_XMLOasisContentImporter_get_implementation", com_sun_star_comp_Writer_XMLOasisContentImporter_get_implementation },
        { "com_sun_star_comp_Writer_XMLOasisImporter_get_implementation", com_sun_star_comp_Writer_XMLOasisImporter_get_implementation },
        { "com_sun_star_comp_Writer_XMLOasisMetaExporter_get_implementation", com_sun_star_comp_Writer_XMLOasisMetaExporter_get_implementation },
        { "com_sun_star_comp_Writer_XMLOasisMetaImporter_get_implementation", com_sun_star_comp_Writer_XMLOasisMetaImporter_get_implementation },
        { "com_sun_star_comp_Writer_XMLOasisSettingsExporter_get_implementation", com_sun_star_comp_Writer_XMLOasisSettingsExporter_get_implementation },
        { "com_sun_star_comp_Writer_XMLOasisSettingsImporter_get_implementation", com_sun_star_comp_Writer_XMLOasisSettingsImporter_get_implementation },
        { "com_sun_star_comp_Writer_XMLOasisStylesExporter_get_implementation", com_sun_star_comp_Writer_XMLOasisStylesExporter_get_implementation },
        { "com_sun_star_comp_Writer_XMLOasisStylesImporter_get_implementation", com_sun_star_comp_Writer_XMLOasisStylesImporter_get_implementation },
        { "com_sun_star_comp_calc_ExcelBiffFormatDetector_get_implementation", com_sun_star_comp_calc_ExcelBiffFormatDetector_get_implementation },
        { "com_sun_star_comp_calc_FormatDetector_get_implementation", com_sun_star_comp_calc_FormatDetector_get_implementation },
        { "com_sun_star_comp_chart2_Axis_get_implementation", com_sun_star_comp_chart2_Axis_get_implementation },
        { "com_sun_star_comp_chart2_ChartController_get_implementation", com_sun_star_comp_chart2_ChartController_get_implementation },
        { "com_sun_star_comp_chart2_ChartDocumentWrapper_get_implementation", com_sun_star_comp_chart2_ChartDocumentWrapper_get_implementation },
        { "com_sun_star_comp_chart2_ChartFrameLoader_get_implementation", com_sun_star_comp_chart2_ChartFrameLoader_get_implementation },
        { "com_sun_star_comp_chart2_ChartModel_get_implementation", com_sun_star_comp_chart2_ChartModel_get_implementation },
        { "com_sun_star_comp_chart2_Diagram_get_implementation", com_sun_star_comp_chart2_Diagram_get_implementation },
        { "com_sun_star_comp_chart2_ErrorBar_get_implementation", com_sun_star_comp_chart2_ErrorBar_get_implementation },
        { "com_sun_star_comp_chart2_LabeledDataSequence_get_implementation", com_sun_star_comp_chart2_LabeledDataSequence_get_implementation },
        { "com_sun_star_comp_chart2_Legend_get_implementation", com_sun_star_comp_chart2_Legend_get_implementation },
        { "com_sun_star_comp_chart2_LinearRegressionCurve_get_implementation", com_sun_star_comp_chart2_LinearRegressionCurve_get_implementation },
        { "com_sun_star_comp_chart2_PolarCoordinateSystem2d_get_implementation", com_sun_star_comp_chart2_PolarCoordinateSystem2d_get_implementation },
        { "com_sun_star_comp_chart2_PolarCoordinateSystem3d_get_implementation", com_sun_star_comp_chart2_PolarCoordinateSystem3d_get_implementation },
        { "com_sun_star_comp_chart2_PolynomialRegressionCurve_get_implementation", com_sun_star_comp_chart2_PolynomialRegressionCurve_get_implementation },
        { "com_sun_star_comp_chart2_PotentialRegressionCurve_get_implementation", com_sun_star_comp_chart2_PotentialRegressionCurve_get_implementation },
        { "com_sun_star_comp_chart2_RegressionEquation_get_implementation", com_sun_star_comp_chart2_RegressionEquation_get_implementation },
        { "com_sun_star_comp_chart2_Title_get_implementation", com_sun_star_comp_chart2_Title_get_implementation },
        { "com_sun_star_comp_chart2_XMLFilter_get_implementation", com_sun_star_comp_chart2_XMLFilter_get_implementation },
        { "com_sun_star_comp_chart_AreaChartType_get_implementation", com_sun_star_comp_chart_AreaChartType_get_implementation },
        { "com_sun_star_comp_chart_BarChartType_get_implementation", com_sun_star_comp_chart_BarChartType_get_implementation },
        { "com_sun_star_comp_chart_BubbleChartType_get_implementation", com_sun_star_comp_chart_BubbleChartType_get_implementation },
        { "com_sun_star_comp_chart_CandleStickChartType_get_implementation", com_sun_star_comp_chart_CandleStickChartType_get_implementation },
        { "com_sun_star_comp_chart_ChartTypeManager_get_implementation", com_sun_star_comp_chart_ChartTypeManager_get_implementation },
        { "com_sun_star_comp_chart_ColumnChartType_get_implementation", com_sun_star_comp_chart_ColumnChartType_get_implementation },
        { "com_sun_star_comp_chart_DataSeries_get_implementation", com_sun_star_comp_chart_DataSeries_get_implementation },
        { "com_sun_star_comp_chart_DataSource_get_implementation", com_sun_star_comp_chart_DataSource_get_implementation },
        { "com_sun_star_comp_chart_FilledNetChartType_get_implementation", com_sun_star_comp_chart_FilledNetChartType_get_implementation },
        { "com_sun_star_comp_chart_FormattedString_get_implementation", com_sun_star_comp_chart_FormattedString_get_implementation },
        { "com_sun_star_comp_chart_GL3DBarChartType_get_implementation", com_sun_star_comp_chart_GL3DBarChartType_get_implementation },
        { "com_sun_star_comp_chart_LineChartType_get_implementation", com_sun_star_comp_chart_LineChartType_get_implementation },
        { "com_sun_star_comp_chart_NetChartType_get_implementation", com_sun_star_comp_chart_NetChartType_get_implementation },
        { "com_sun_star_comp_chart_PieChartType_get_implementation", com_sun_star_comp_chart_PieChartType_get_implementation },
        { "com_sun_star_comp_chart_ScatterChartType_get_implementation", com_sun_star_comp_chart_ScatterChartType_get_implementation },
        { "com_sun_star_comp_comphelper_OPropertyBag", com_sun_star_comp_comphelper_OPropertyBag },
        { "com_sun_star_comp_dba_ORowSet_get_implementation", com_sun_star_comp_dba_ORowSet_get_implementation },
        { "com_sun_star_comp_draw_FormatDetector_get_implementation", com_sun_star_comp_draw_FormatDetector_get_implementation },
        { "com_sun_star_comp_embed_OLESimpleStorage", com_sun_star_comp_embed_OLESimpleStorage },
        { "com_sun_star_comp_extensions_xml_sax_FastParser_get_implementation", com_sun_star_comp_extensions_xml_sax_FastParser_get_implementation },
        { "com_sun_star_comp_extensions_xml_sax_ParserExpat_get_implementation", com_sun_star_comp_extensions_xml_sax_ParserExpat_get_implementation },
        { "com_sun_star_comp_filters_PlainTextFilterDetect_get_implementation", com_sun_star_comp_filters_PlainTextFilterDetect_get_implementation },
        { "com_sun_star_comp_forms_FormOperations_get_implementation", com_sun_star_comp_forms_FormOperations_get_implementation },
        { "com_sun_star_comp_forms_ODatabaseForm_get_implementation", com_sun_star_comp_forms_ODatabaseForm_get_implementation },
        { "com_sun_star_comp_forms_OFormattedFieldWrapper_ForcedFormatted_get_implementation", com_sun_star_comp_forms_OFormattedFieldWrapper_ForcedFormatted_get_implementation },
        { "com_sun_star_comp_forms_ORichTextModel_get_implementation", com_sun_star_comp_forms_ORichTextModel_get_implementation },
        { "com_sun_star_comp_forms_OScrollBarModel_get_implementation", com_sun_star_comp_forms_OScrollBarModel_get_implementation },
        { "com_sun_star_comp_forms_OSpinButtonModel_get_implementation", com_sun_star_comp_forms_OSpinButtonModel_get_implementation },
        { "com_sun_star_comp_framework_AutoRecovery_get_implementation", com_sun_star_comp_framework_AutoRecovery_get_implementation },
        { "com_sun_star_comp_framework_Desktop_get_implementation", com_sun_star_comp_framework_Desktop_get_implementation },
        { "com_sun_star_comp_framework_DocumentAcceleratorConfiguration_get_implementation", com_sun_star_comp_framework_DocumentAcceleratorConfiguration_get_implementation },
        { "com_sun_star_comp_framework_Frame_get_implementation", com_sun_star_comp_framework_Frame_get_implementation },
        { "com_sun_star_comp_framework_GlobalAcceleratorConfiguration_get_implementation", com_sun_star_comp_framework_GlobalAcceleratorConfiguration_get_implementation },
        { "com_sun_star_comp_framework_JobExecutor_get_implementation", com_sun_star_comp_framework_JobExecutor_get_implementation },
        { "com_sun_star_comp_framework_LayoutManager_get_implementation", com_sun_star_comp_framework_LayoutManager_get_implementation },
        { "com_sun_star_comp_framework_ModuleAcceleratorConfiguration_get_implementation", com_sun_star_comp_framework_ModuleAcceleratorConfiguration_get_implementation },
        { "com_sun_star_comp_framework_ModuleManager_get_implementation", com_sun_star_comp_framework_ModuleManager_get_implementation },
        { "com_sun_star_comp_framework_ModuleUIConfigurationManagerSupplier_get_implementation", com_sun_star_comp_framework_ModuleUIConfigurationManagerSupplier_get_implementation },
        { "com_sun_star_comp_framework_ModuleUIConfigurationManager_get_implementation", com_sun_star_comp_framework_ModuleUIConfigurationManager_get_implementation },
        { "com_sun_star_comp_framework_PathSettings_get_implementation", com_sun_star_comp_framework_PathSettings_get_implementation },
        { "com_sun_star_comp_framework_PathSubstitution_get_implementation", com_sun_star_comp_framework_PathSubstitution_get_implementation },
        { "com_sun_star_comp_framework_SoundHandler_get_implementation", com_sun_star_comp_framework_SoundHandler_get_implementation },
        { "com_sun_star_comp_framework_StatusIndicatorFactory_get_implementation", com_sun_star_comp_framework_StatusIndicatorFactory_get_implementation },
        { "com_sun_star_comp_framework_TaskCreator_get_implementation", com_sun_star_comp_framework_TaskCreator_get_implementation },
        { "com_sun_star_comp_framework_ToolBarControllerFactory_get_implementation", com_sun_star_comp_framework_ToolBarControllerFactory_get_implementation },
        { "com_sun_star_comp_framework_UIConfigurationManager_get_implementation", com_sun_star_comp_framework_UIConfigurationManager_get_implementation },
        { "com_sun_star_comp_framework_UIElementFactoryManager_get_implementation", com_sun_star_comp_framework_UIElementFactoryManager_get_implementation },
        { "com_sun_star_comp_framework_URLTransformer_get_implementation", com_sun_star_comp_framework_URLTransformer_get_implementation },
        { "com_sun_star_comp_framework_WindowStateConfiguration_get_implementation", com_sun_star_comp_framework_WindowStateConfiguration_get_implementation },
        { "com_sun_star_comp_graphic_GraphicProvider_get_implementation", com_sun_star_comp_graphic_GraphicProvider_get_implementation },
        { "com_sun_star_comp_graphic_PrimitiveFactory2D_get_implementation", com_sun_star_comp_graphic_PrimitiveFactory2D_get_implementation },
        { "com_sun_star_comp_logging_SimpleLogRing", com_sun_star_comp_logging_SimpleLogRing },
        { "com_sun_star_comp_office_FrameLoader_get_implementation", com_sun_star_comp_office_FrameLoader_get_implementation },
        { "com_sun_star_comp_oox_xls_ExcelFilter_get_implementation", com_sun_star_comp_oox_xls_ExcelFilter_get_implementation },
        { "com_sun_star_comp_oox_xls_FormulaParser_get_implementation", com_sun_star_comp_oox_xls_FormulaParser_get_implementation },
        { "com_sun_star_comp_rendering_CanvasFactory_get_implementation", com_sun_star_comp_rendering_CanvasFactory_get_implementation },
        { "com_sun_star_comp_sfx2_AppDispatchProvider_get_implementation", com_sun_star_comp_sfx2_AppDispatchProvider_get_implementation },
        { "com_sun_star_comp_sfx2_DocumentTemplates_get_implementation", com_sun_star_comp_sfx2_DocumentTemplates_get_implementation },
        { "com_sun_star_comp_sfx2_GlobalEventBroadcaster_get_implementation", com_sun_star_comp_sfx2_GlobalEventBroadcaster_get_implementation },
#if HAVE_FEATURE_SCRIPTING
        { "com_sun_star_comp_sfx2_ScriptLibraryContainer_get_implementation", com_sun_star_comp_sfx2_ScriptLibraryContainer_get_implementation },
#endif
        { "com_sun_star_comp_stoc_Introspection_get_implementation", com_sun_star_comp_stoc_Introspection_get_implementation },
        { "com_sun_star_comp_stoc_OServiceManagerWrapper_get_implementation", com_sun_star_comp_stoc_OServiceManagerWrapper_get_implementation },
        { "com_sun_star_comp_stoc_TypeConverter_get_implementation", com_sun_star_comp_stoc_TypeConverter_get_implementation },
        { "com_sun_star_comp_task_OfficeRestartManager", com_sun_star_comp_task_OfficeRestartManager },
        { "com_sun_star_comp_uri_ExternalUriReferenceTranslator_get_implementation", com_sun_star_comp_uri_ExternalUriReferenceTranslator_get_implementation },
        { "com_sun_star_comp_uri_UriReferenceFactory_get_implementation", com_sun_star_comp_uri_UriReferenceFactory_get_implementation },
        { "com_sun_star_comp_uri_UriSchemeParser_vndDOTsunDOTstarDOTexpand_get_implementation", com_sun_star_comp_uri_UriSchemeParser_vndDOTsunDOTstarDOTexpand_get_implementation },
        { "com_sun_star_comp_uri_UriSchemeParser_vndDOTsunDOTstarDOTscript_get_implementation", com_sun_star_comp_uri_UriSchemeParser_vndDOTsunDOTstarDOTscript_get_implementation },
        { "com_sun_star_comp_uui_UUIInteractionHandler_get_implementation", com_sun_star_comp_uui_UUIInteractionHandler_get_implementation },
        { "com_sun_star_comp_writer_FormatDetector_get_implementation", com_sun_star_comp_writer_FormatDetector_get_implementation },
        { "com_sun_star_drawing_EnhancedCustomShapeEngine_get_implementation", com_sun_star_drawing_EnhancedCustomShapeEngine_get_implementation },
        { "com_sun_star_drawing_SvxShapeCollection_get_implementation", com_sun_star_drawing_SvxShapeCollection_get_implementation },
        { "com_sun_star_extensions_xml_sax_Writer_get_implementation", com_sun_star_extensions_xml_sax_Writer_get_implementation },
        { "com_sun_star_form_Model_get_implementation", com_sun_star_form_Model_get_implementation },
        { "com_sun_star_form_OButtonControl_get_implementation", com_sun_star_form_OButtonControl_get_implementation },
        { "com_sun_star_form_OButtonModel_get_implementation", com_sun_star_form_OButtonModel_get_implementation },
        { "com_sun_star_form_OCheckBoxControl_get_implementation", com_sun_star_form_OCheckBoxControl_get_implementation },
        { "com_sun_star_form_OCheckBoxModel_get_implementation", com_sun_star_form_OCheckBoxModel_get_implementation },
        { "com_sun_star_form_OComboBoxControl_get_implementation", com_sun_star_form_OComboBoxControl_get_implementation },
        { "com_sun_star_form_OComboBoxModel_get_implementation", com_sun_star_form_OComboBoxModel_get_implementation },
        { "com_sun_star_form_ODateControl_get_implementation", com_sun_star_form_ODateControl_get_implementation },
        { "com_sun_star_form_ODateModel_get_implementation", com_sun_star_form_ODateModel_get_implementation },
        { "com_sun_star_form_OEditControl_get_implementation", com_sun_star_form_OEditControl_get_implementation },
        { "com_sun_star_form_OEditModel_get_implementation", com_sun_star_form_OEditModel_get_implementation },
        { "com_sun_star_form_OFixedTextModel_get_implementation", com_sun_star_form_OFixedTextModel_get_implementation },
        { "com_sun_star_form_OFormsCollection_get_implementation", com_sun_star_form_OFormsCollection_get_implementation },
        { "com_sun_star_form_OGridControlModel_get_implementation", com_sun_star_form_OGridControlModel_get_implementation },
        { "com_sun_star_form_OGroupBoxModel_get_implementation", com_sun_star_form_OGroupBoxModel_get_implementation },
        { "com_sun_star_form_OListBoxModel_get_implementation", com_sun_star_form_OListBoxModel_get_implementation },
        { "com_sun_star_form_ONumericModel_get_implementation", com_sun_star_form_ONumericModel_get_implementation },
        { "com_sun_star_form_ORadioButtonModel_get_implementation", com_sun_star_form_ORadioButtonModel_get_implementation },
        { "com_sun_star_form_XForms_get_implementation", com_sun_star_form_XForms_get_implementation },
        { "com_sun_star_graphic_GraphicObject_get_implementation", com_sun_star_graphic_GraphicObject_get_implementation },
        { "com_sun_star_i18n_BreakIterator_Unicode_get_implementation", com_sun_star_i18n_BreakIterator_Unicode_get_implementation },
        { "com_sun_star_i18n_BreakIterator_get_implementation", com_sun_star_i18n_BreakIterator_get_implementation },
        { "com_sun_star_i18n_CharacterClassification_Unicode_get_implementation", com_sun_star_i18n_CharacterClassification_Unicode_get_implementation },
        { "com_sun_star_i18n_CharacterClassification_get_implementation", com_sun_star_i18n_CharacterClassification_get_implementation },
        { "com_sun_star_i18n_Collator_get_implementation", com_sun_star_i18n_Collator_get_implementation },
        { "com_sun_star_i18n_InputSequenceChecker_get_implementation", com_sun_star_i18n_InputSequenceChecker_get_implementation },
        { "com_sun_star_i18n_LocaleDataImpl_get_implementation", com_sun_star_i18n_LocaleDataImpl_get_implementation },
        { "com_sun_star_i18n_NativeNumberSupplier_get_implementation", com_sun_star_i18n_NativeNumberSupplier_get_implementation },
        { "com_sun_star_i18n_NumberFormatCodeMapper_get_implementation", com_sun_star_i18n_NumberFormatCodeMapper_get_implementation },
        { "com_sun_star_i18n_OrdinalSuffix_get_implementation", com_sun_star_i18n_OrdinalSuffix_get_implementation },
        { "com_sun_star_i18n_Transliteration_IGNORE_CASE_get_implementation", com_sun_star_i18n_Transliteration_IGNORE_CASE_get_implementation },
        { "com_sun_star_i18n_Transliteration_IGNORE_KANA_get_implementation", com_sun_star_i18n_Transliteration_IGNORE_KANA_get_implementation },
        { "com_sun_star_i18n_Transliteration_IGNORE_WIDTH_get_implementation", com_sun_star_i18n_Transliteration_IGNORE_WIDTH_get_implementation },
        { "com_sun_star_i18n_Transliteration_get_implementation", com_sun_star_i18n_Transliteration_get_implementation },
        { "com_sun_star_text_DefaultNumberingProvider_get_implementation", com_sun_star_text_DefaultNumberingProvider_get_implementation },
        { "com_sun_star_uno_util_numbers_SvNumberFormatsSupplierServiceObject_get_implementation", com_sun_star_uno_util_numbers_SvNumberFormatsSupplierServiceObject_get_implementation },
        { "com_sun_star_uno_util_numbers_SvNumberFormatterServiceObject_get_implementation", com_sun_star_uno_util_numbers_SvNumberFormatterServiceObject_get_implementation },
        { "com_sun_star_util_comp_FinalThreadManager_get_implementation", com_sun_star_util_comp_FinalThreadManager_get_implementation },
#if HAVE_FEATURE_SCRIPTING
        { "ooo_vba_VBAToOOEventDesc_get_implementation", ooo_vba_VBAToOOEventDesc_get_implementation },
#endif
        { "org_apache_openoffice_comp_framework_ContextChangeEventMultiplexer_get_implementation", org_apache_openoffice_comp_framework_ContextChangeEventMultiplexer_get_implementation },
        { "stardiv_Toolkit_StdTabController_get_implementation", stardiv_Toolkit_StdTabController_get_implementation },
        { "stardiv_Toolkit_UnoButtonControl_get_implementation", stardiv_Toolkit_UnoButtonControl_get_implementation },
        { "stardiv_Toolkit_UnoCheckBoxControl_get_implementation", stardiv_Toolkit_UnoCheckBoxControl_get_implementation },
        { "stardiv_Toolkit_UnoComboBoxControl_get_implementation", stardiv_Toolkit_UnoComboBoxControl_get_implementation },
        { "stardiv_Toolkit_UnoControlButtonModel_get_implementation", stardiv_Toolkit_UnoControlButtonModel_get_implementation },
        { "stardiv_Toolkit_UnoControlCheckBoxModel_get_implementation", stardiv_Toolkit_UnoControlCheckBoxModel_get_implementation },
        { "stardiv_Toolkit_UnoControlComboBoxModel_get_implementation", stardiv_Toolkit_UnoControlComboBoxModel_get_implementation },
        { "stardiv_Toolkit_UnoControlContainerModel_get_implementation", stardiv_Toolkit_UnoControlContainerModel_get_implementation },
        { "stardiv_Toolkit_UnoControlContainer_get_implementation", stardiv_Toolkit_UnoControlContainer_get_implementation },
        { "stardiv_Toolkit_UnoControlDateFieldModel_get_implementation", stardiv_Toolkit_UnoControlDateFieldModel_get_implementation },
        { "stardiv_Toolkit_UnoControlDialogModel_get_implementation", stardiv_Toolkit_UnoControlDialogModel_get_implementation },
        { "stardiv_Toolkit_UnoControlFixedTextModel_get_implementation", stardiv_Toolkit_UnoControlFixedTextModel_get_implementation },
        { "stardiv_Toolkit_UnoControlFormattedFieldModel_get_implementation", stardiv_Toolkit_UnoControlFormattedFieldModel_get_implementation },
        { "stardiv_Toolkit_UnoControlGroupBoxModel_get_implementation", stardiv_Toolkit_UnoControlGroupBoxModel_get_implementation },
        { "stardiv_Toolkit_UnoControlListBoxModel_get_implementation", stardiv_Toolkit_UnoControlListBoxModel_get_implementation },
        { "stardiv_Toolkit_UnoControlNumericFieldModel_get_implementation", stardiv_Toolkit_UnoControlNumericFieldModel_get_implementation },
        { "stardiv_Toolkit_UnoControlRadioButtonModel_get_implementation", stardiv_Toolkit_UnoControlRadioButtonModel_get_implementation },
        { "stardiv_Toolkit_UnoControlScrollBarModel_get_implementation", stardiv_Toolkit_UnoControlScrollBarModel_get_implementation },
        { "stardiv_Toolkit_UnoDateFieldControl_get_implementation", stardiv_Toolkit_UnoDateFieldControl_get_implementation },
        { "stardiv_Toolkit_UnoSpinButtonModel_get_implementation", stardiv_Toolkit_UnoSpinButtonModel_get_implementation },
        { "stardiv_Toolkit_VCLXPointer_get_implementation", stardiv_Toolkit_VCLXPointer_get_implementation },
        { "stardiv_Toolkit_VCLXToolkit_get_implementation", stardiv_Toolkit_VCLXToolkit_get_implementation },

        { 0, 0 }
    };

    return map;
}

}
